quotes = [
    { "Second-hand gold is as good as new.", "Ken Alstad" },
    { "Because gold is honest money it is disliked by dishonest men.", "Ron Paul" },
    { "Gold makes the ugly beautiful.", "Moliere" },
    { "A mask of gold hides all deformities.", "Thomas Dekker" },
    { "Gold gathers more than a shovel.", "Edward Counsel" },
    { "Gold often commends the unworthy.", "Edward Counsel" },
    { "Gold does not rust on the ground, and rocks don't get soaked in the rain.", "Turkish roverb"},
    { "That is gold which is worth gold.", "George Herbert" },
    { "Gold authenticity can only be tested under maximum fire. The same holds true with regard to manhood.", "Moutasem Algharati" },
    { "The desire for gold is the most universal and deeply rooted commercial instinct of the human race.", "Gerald M. Loeb" },
    { "We must learn who is gold, and who is gold plated.", "unknown" },
    { "Pure gold does not rust. Only gold alloys do so. You may have golden dreams. But if you go in the company of toxic people, your become 'a gold alloy' and what that means is that you can rust at any time!", "Israelmore Ayivor" },
    { "If gold rusts, what then can iron do?", "Geoffrey Chaucer" },
    { "All that glitters is not gold.", "English Proverb" },
    { "There is gold everywhere, most people are not trained to see it.", "Robert Kiyosaki" },
    { "Hunger for gold is made greater as more gold is acquired.", "Aurelius Clemens Prudentius" },
    { "Gold makes monsters of men.", "Erin Bowman" },
    { "More gold has been mined from the thoughts of men than has been taken from the earth.", "Napoleon Hill" },
    {"Are you looking for gold, friend? Look around you; anything useful to you is pure gold, pure silver!", "Mehmet Murat ildan" },
    { "Nothing gold can stay.", "Robert Frost" },
    { "Those that go gold into the furnace will come out no worse.", "Matthew Henry" },
    { "Gold like the sun, which melts wax, but hardens clay, expands great souls.", "Antoine Rivarol" },
    { "Gold gives to the ugliest thing a certain charming air, For that without it were else a miserable affair.", "Jean Baptiste Poquelin Moliere"},
    { "No gold glitters like that which is our own.", "Eliza Cook" },
    { "Gold opens all locks, no lock will hold against the power of gold.", "George Herbert" },
    { "Gold may shine; but it has no true light.", "Kristian Goldmund Aumann" },
    { "As every thread of gold is valuable, so is every moment of time.", "English Proverb" },
    { "All the gold which is under or upon the earth is not enough to give in exchange for virtue.", "Plato" },
    { "Gold is money. Everything else is credit.", "J. P. Morgan" },
    { "Gold begets in brethren hate; Gold in families debate; Gold does friendship separate; Gold does civil wars create.", "Abraham Cowley"}
]
